version: '3.4'

services:
  backendapi:
    image: backendapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80  
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=Medical;User Id=sa;Password=Password123;TrustServerCertificate=True
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    container_name: mssql
    ports:
      - "1433:1433"