version: '3.8'

services:
  backendapi:
    image: ${DOCKER_REGISTRY-}backendapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db,1433;Database=Medical;User Id=saa;Password=Password123;TrustServerCertificate=True
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mynetwork
 

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
 
