version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=db;Database=Medical;User Id=saa;Password=Password123;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "5000:5000"
    depends_on:
      - db
   
 

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    
